

# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: repo_devops 
    type: git
    name: Analytics/sync_github
    ref: main

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

- checkout: self
  persistCredentials: true
  
- checkout: repo_devops  

- script: dir $(Build.SourcesDirectory)
  displayName: 'dir do REPO********'

- script: cd draw_io_integration/ | ls
  displayName: 'CD e LS do REPO********'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      cd draw_io_integration/ |ls
      git remote add --mirror=fetch upstream repo_devops
      git fetch upstream --tags
      git push origin --all
      echo Hello world

